### PR TITLE
So many damn endpoints

### PR DESCRIPTION
**Pull request by josephkhawly**

### CODE REVIEW

**Comment by thesoupgirl** [comment]
I've only checked creating an activity.  It works, but it needs to add the group leader to the list of members in the group

**Comment by josephkhawly** [comment]
Endpoints in this PR:

- Open group: POST {id}/open, id in route is activityId, userId in form
- Close group: POST {id}/close, id in route is activityId, userId in form
- create activity: POST /api/activities/{id}/createactivity, name, description, latitude, longitude, category, maxSize, status, and avatar in form
- delete activity: POST /api/activities/{id}/deleteactivity, id in route is activityId, userId in form
- find activities: GET /api/activities/{id}/{dist}/search
- Leave group: POST /api/chat/{id}/leave, id in route is activityId, userId in form

**Comment by thesoupgirl** [comment]
find activities works!

**Comment by josephkhawly** [comment]
I made another endpoint.

GET /api/activities/{id}/getactivities

Get all the activities a user is in. UserId should be provided in route string.

**Review by thesoupgirl — APPROVED** [review]

**Pull request merged**
